[workspace]
members = [
    "core",
    "cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
memmap2 = "0.9.10"
rayon = "1.12.0"
rustc-hash = "2.1.2"
s2 = "0.0.13"
sha2 = "0.10.9"
tempfile = "3.27.0"
tiff = "0.11.3"
